# Generated by Django 3.2.4 on 2021-08-10 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='tags',
        ),
    ]
