# Generated by Django 3.2.4 on 2021-08-25 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tag',
            table=None,
        ),
    ]
