# Generated by Django 3.2.4 on 2021-08-06 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'image_tag',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_index=True, default='Anonymous', max_length=255, null=True, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, default='Anonymous', max_length=140, verbose_name='Name')),
                ('tag', models.ManyToManyField(blank=True, through='posts.Image_tag', to='posts.Images')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ManyToManyField(blank=True, through='posts.Image_tag', to='posts.Tags'),
        ),
        migrations.AddField(
            model_name='image_tag',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.images'),
        ),
        migrations.AddField(
            model_name='image_tag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.tags'),
        ),
    ]
