# Generated by Django 3.2.4 on 2021-08-08 01:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210806_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='name',
        ),
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.ManyToManyField(blank=True, db_index=True, default='Anonymous', through='posts.Image_tag', to='posts.Tags'),
        ),
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
